### ISSUE TITLE
how to work with sshfs

### ISSUE THREAD

**Issue by songouyang** [rasmunk/jupyter_service#3]
i want to deploy https://github.com/rasmunk/jupyter_service/blob/master/docker-compose.yml 
i edit https://github.com/rasmunk/jupyter_service/blob/master/hub/jupyterhub_config.py
replace {sshcmd} with `ssh ouyangsong@10.X.X.X:~/jupyter/`，and replace {id_rsa} with `-----BEGIN RSA PRIVATE.....` and also execute setup_jup_crypt_secret.sh before stack deploy.
but i cannot swpan, the service jupyter-ouyang cannot start, the REPLICAS is 0/1 and it doesn't generate contrainer.

**Comment by rasmunk** [comment]
To begin with I would recommend setting the password option instead, at least while debugging, or point it directly at the 'IdentityFile' when configuring a static configuration for authentication. The id_rsa flag is only supposed to be used with a dynamic key setup and should be not be used for a static configuration.

Also, if you are using the 'rasmunk/sshfs:latest' driver config, ensure that this plugin is installed on the system that hosts your jupyterhub. See https://github.com/rasmunk/docker-volume-sshfs for information on how to do this.

**Comment by songouyang** [comment]
@rasmunk i figure out, it's big_wirte [param](https://github.com/rasmunk/jupyter_service/blob/master/tests/sshfs-mounter/hub/jupyterhub_config.py#L24), i remove it, and success.
by the way, how to do ACL for different, i don't want to make it available to every. i edit sshfs conf, and can't separate workspace.
```python
mounts = [SSHFSMounter({
                       'type': 'volume',
                       'driver_config': 'rasmunk/sshfs:latest',
                       'driver_options': {'sshcmd': 'XXXX', 'password': 'XXXXX',
                       'one_time': 'True',
                       'allow_other': 'False'},     'source': '{username}',
                       'target': notebook_dir})]
```
